---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${USER_NAME}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin *";
      more_set_headers "Access-Control-Allow-Methods 'GET, POST, OPTIONS'";
      more_set_headers "Access-Control-Allow-Headers 'Content-Type, Authorization'";
      more_set_headers "Content-Security-Policy: frame-ancestors *;";
spec:
  ingressClassName: nginx
  rules:
    - host: ${USER_NAME}.el-khayali.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${USER_NAME}
                port:
                  number: 8080
