apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${USER_NAME}
  labels:
    app: ${USER_NAME}
spec:
  replicas: 2

  selector:
    matchLabels:
      app: ${USER_NAME}

  template:
    metadata:
      labels:
        app: ${USER_NAME}
    spec:
      containers:
        - name: demo-app
          image: 479165877194.dkr.ecr.us-east-1.amazonaws.com/eks-demo-app:latest

          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
