---
apiVersion: v1
kind: Pod
metadata:
  name: ${USER_NAME}
spec:
  containers:
  - name: demo-app
    image: 479165877194.dkr.ecr.us-east-1.amazonaws.com/eks-demo-app:latest
        
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi